import { test, expect } from '@playwright/test';
import { mkdirSync, readFileSync, writeFileSync, realpathSync } from 'node:fs';
import { resolve, relative, isAbsolute } from 'node:path';
import { createHash } from 'node:crypto';
import { Painting } from '../src/painting/engine';
import { executeStroke } from '../src/experiment/plan';
import { ready, draw, digest } from './helpers';
import { experimentDigest, experimentPng, storedDraft } from './e1-helpers';

test('quality complete real workflow, exact replay, paused export and preserved M2', async ({ page }) => {
  const dir = resolve(process.env.M1_ARTIFACT_DIR!); mkdirSync(dir,{recursive:true});
  const file = process.env.E1_QUALITY_INPUT || 'artifacts/e1/finished-quality/fixtures/portrait-holdout.jpg';
  // Explicit private input implies private reports, video and all derived output.
  if(process.env.E1_QUALITY_INPUT) {
    const repo=realpathSync('.'), output=realpathSync(dir), rel=relative(repo,output);
    expect(!!rel&&(rel==='..'||rel.startsWith('..\\')||rel.startsWith('../')||isAbsolute(rel))).toBe(true);
  }
  const errors:string[]=[],external:string[]=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',r=>{const u=r.request().url();if(/^(http:\/\/127\.0\.0\.1:5174\/|blob:|data:)/.test(u))return r.continue();external.push(u);return r.abort();});
  await ready(page);await draw(page,[{x:300,y:400},{x:600,y:460}]);
  await expect(page.getByTestId('save-state')).toHaveAttribute('data-phase','saved',{timeout:15000});
  const main=await digest(page),draft=await storedDraft(page);
  await page.getByRole('button',{name:'图片自动绘制 · 实验',exact:true}).click();
  await page.getByRole('button',{name:'成品细节 · 实验',exact:true}).click();
  await page.getByLabel('选择本地图片',{exact:true}).setInputFiles(file);
  await page.getByLabel('播放速度',{exact:true}).selectOption('4');
  await page.screenshot({path:`${dir}/composition.png`,fullPage:true});
  await page.getByRole('button',{name:'确认构图，准备笔与颜色',exact:true}).click();
  const start=page.getByRole('button',{name:'确认准备，开始绘制',exact:true});await expect(start).toBeEnabled({timeout:130000});
  const plan=await page.evaluate(()=>window.__experiment!.plan!);
  expect(plan.plannerVersion).toBe('e1-finished-quality-1');
  const blank=await experimentDigest(page); await page.waitForTimeout(200);expect(await experimentDigest(page)).toEqual(blank);
  await page.screenshot({path:`${dir}/prepared.png`,fullPage:true});
  const begin=Date.now();await start.click();
  await page.waitForFunction(()=>{const p=window.__experiment!.player!;if(p.index>12){p.pause();return true;}return false;});
  const partial=await experimentDigest(page);await page.waitForTimeout(250);expect(await experimentDigest(page)).toEqual(partial);
  const part=await experimentPng(page,`${dir}/partial.png`);
  await page.getByRole('button',{name:'展开原图',exact:true}).click();
  expect((await experimentPng(page,`${dir}/partial-with-reference.png`)).equals(part)).toBe(true);
  await page.getByRole('button',{name:'原版 · 油画笔触',exact:true}).click();
  await page.getByRole('button',{name:'确认构图，准备笔与颜色',exact:true}).click();
  await page.getByRole('button',{name:'取消，保留实验画作',exact:true}).click();expect(await experimentDigest(page)).toEqual(partial);
  await page.getByRole('button',{name:'成品细节 · 实验',exact:true}).click();
  await page.getByRole('button',{name:'收起原图',exact:true}).click();
  await page.getByRole('button',{name:'继续绘制',exact:true}).click();
  await page.waitForFunction(()=>window.__experiment?.player?.state==='complete',undefined,{timeout:1200000});
  const wallMs=Date.now()-begin, final=await experimentDigest(page);
  expect(await page.evaluate(()=>window.__experiment!.player!.heldBrushId)).toBeNull();
  const exportStart=Date.now(), download=page.waitForEvent('download');await page.getByRole('button',{name:'导出实验 PNG',exact:true}).click();await(await download).saveAs(`${dir}/final.png`);const downloadWallMs=Date.now()-exportStart;
  const png=readFileSync(`${dir}/final.png`);expect(png.readUInt32BE(16)).toBe(1024);expect(png.readUInt32BE(20)).toBe(1024);
  await page.screenshot({path:`${dir}/finished-reference-hidden.png`,fullPage:true});
  await page.getByRole('button',{name:'展开原图',exact:true}).click();
  expect((await experimentPng(page,`${dir}/final-with-reference.png`)).equals(png)).toBe(true);
  await page.screenshot({path:`${dir}/finished-reference-visible.png`,fullPage:true});
  const measurements=await page.evaluate(()=>({planningMs:window.__experiment!.planningMs,timing:window.__experiment!.player!.timing,metrics:window.__experiment!.player!.metrics,memory:window.__experiment!.painting.memory(),renderer:window.__experiment!.renderer.info(),userAgent:navigator.userAgent}));
  const cpu=new Painting(false);plan.strokes.forEach(s=>executeStroke(cpu,s));
  const independent={color:createHash('sha256').update(cpu.color).digest('hex'),height:createHash('sha256').update(new Uint8Array(cpu.height.buffer)).digest('hex')};expect(independent).toEqual(final);
  const expectedFile=process.env.E1_QUALITY_EXPECTED;
  if(expectedFile) expect(JSON.parse(readFileSync(expectedFile,'utf8')).summaries.find((s:{approach:string})=>s.approach==='quality').state).toEqual(final);
  await page.evaluate(()=>window.__experiment!.renderer.gl!.getExtension('WEBGL_lose_context')!.loseContext());
  await expect(page.getByText('正在使用简化画布显示，局部材质光照暂不可用。')).toBeVisible();expect(await experimentDigest(page)).toEqual(final);
  await experimentPng(page,`${dir}/fallback.png`);
  await page.getByRole('button',{name:'返回画室',exact:true}).click();await page.getByRole('button',{name:'留在实验',exact:true}).click();expect(await experimentDigest(page)).toEqual(final);
  await page.getByRole('button',{name:'返回画室',exact:true}).click();await page.getByRole('button',{name:'确认退出实验',exact:true}).click();expect(await digest(page)).toEqual(main);expect(await storedDraft(page)).toEqual(draft);
  expect(errors).toEqual([]);expect(external).toEqual([]);
  writeFileSync(`${dir}/plan.json`,JSON.stringify(plan));
  writeFileSync(`${dir}/results.json`,JSON.stringify({status:'通过',final,independent,wallMs,downloadWallMs,...measurements,external,errors,note:'Real 4x recording includes manual test pauses and export. Action/draw schedule milliseconds are consumed scheduling time, not wall-clock CPU or latency. Independent unrecorded performance reported separately.',humanQuality:'待用户确认'},null,2));
  const video=page.video();await page.close();if(video)await video.saveAs(`${dir}/process.webm`);
});
