import { test, expect } from '@playwright/test';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { ready, digest, draw } from './helpers';
import { experimentDigest, experimentPng, storedDraft } from './e1-helpers';

test('switchable mode keeps original plan exact, preserves artwork on cancel and executes the new plan', async ({page})=>{
  const dir=`${process.env.M1_ARTIFACT_DIR || 'artifacts/e1/structure-mode/local'}/switching`; mkdirSync(dir,{recursive:true});
  await ready(page); await draw(page,[{x:300,y:400},{x:550,y:430}]);
  await expect(page.getByTestId('save-state')).toHaveAttribute('data-phase','saved',{timeout:15000});
  const main=await digest(page), draft=await storedDraft(page);
  await page.getByRole('button',{name:'图片自动绘制 · 实验',exact:true}).click();
  const original=page.getByRole('button',{name:'原版 · 油画笔触',exact:true}), structured=page.getByRole('button',{name:'结构优先 · 实验',exact:true});
  await expect(original).toHaveAttribute('aria-pressed','true');
  await page.getByLabel('选择本地图片',{exact:true}).setInputFiles('artifacts/e1/fixtures/landscape.jpg');
  await page.getByRole('button',{name:'确认构图，准备笔与颜色',exact:true}).click();
  const start=page.getByRole('button',{name:'确认准备，开始绘制',exact:true}); await expect(start).toBeEnabled({timeout:130000});
  const old=await page.evaluate(()=>JSON.stringify(window.__experiment!.plan));
  expect(JSON.parse(old)).toEqual(JSON.parse(readFileSync('artifacts/e1/prepared-studio/c/landscape/plan.json','utf8')));
  await page.getByLabel('播放速度',{exact:true}).selectOption('4'); await start.click();
  await page.waitForFunction(()=>{const p=window.__experiment!.player!; if(p.index>=12){p.pause();return true;}return false;});
  const before=await experimentDigest(page);
  await structured.click(); expect(await experimentDigest(page)).toEqual(before);
  await expect(page.getByRole('button',{name:'继续绘制',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'确认构图，准备笔与颜色',exact:true}).click();
  await page.getByRole('button',{name:'取消，保留实验画作',exact:true}).click(); expect(await experimentDigest(page)).toEqual(before);
  await original.click(); await expect(page.getByRole('button',{name:'继续绘制',exact:true})).toBeEnabled();
  expect(await page.evaluate(()=>JSON.stringify(window.__experiment!.plan))).toBe(old);
  await structured.click(); await page.getByRole('button',{name:'确认构图，准备笔与颜色',exact:true}).click();
  await page.getByRole('button',{name:'确认替换实验画作',exact:true}).click(); await expect(start).toBeEnabled({timeout:130000});
  expect(await page.evaluate(()=>window.__experiment!.plan!.plannerVersion)).toBe('e1-structure-1');
  await page.screenshot({path:`${dir}/mode-prepared.png`,fullPage:true}); await start.click();
  await page.waitForFunction(()=>{const p=window.__experiment!.player!;if(p.index>=30){p.pause();return true;}return false;});
  const partial=await experimentDigest(page); await page.waitForTimeout(250); expect(await experimentDigest(page)).toEqual(partial);
  const png=await experimentPng(page,`${dir}/actual-partial.png`);
  await page.getByRole('button',{name:'展开原图',exact:true}).click(); expect((await experimentPng(page,`${dir}/reference-visible.png`)).equals(png)).toBe(true);
  await page.evaluate(()=>window.__experiment!.renderer.gl!.getExtension('WEBGL_lose_context')!.loseContext());
  await expect(page.getByText('正在使用简化画布显示，局部材质光照暂不可用。')).toBeVisible(); expect(await experimentDigest(page)).toEqual(partial);
  await experimentPng(page,`${dir}/fallback-partial.png`); expect(await experimentDigest(page)).toEqual(partial);
  await page.getByRole('button',{name:'继续绘制',exact:true}).click();
  await page.waitForFunction(()=>{const p=window.__experiment!.player!;if(p.index>=40){p.pause();return true;}return false;});
  expect(await experimentDigest(page)).not.toEqual(partial);
  await page.getByRole('button',{name:'返回画室',exact:true}).click(); await page.getByRole('button',{name:'确认退出实验',exact:true}).click();
  expect(await digest(page)).toEqual(main); expect(await storedDraft(page)).toEqual(draft);
  writeFileSync(`${dir}/results.json`,JSON.stringify({status:'通过',originalPlanExact:true,partial,main,draft,note:'Actual UI partial process with context-loss export and continued painting; complete fixed plans recorded separately.'},null,2));
  const video=page.video(); await page.close(); if(video) await video.saveAs(`${dir}/process.webm`);
});
