import type { Brush } from '../painting/engine';
import { sunsetSteps, type GuideState } from './sunset';

export function Guide({ state, change, start, recommend, complete }: { state: GuideState; change: (state: GuideState) => void; start: () => void; recommend: (brush: Partial<Brush>) => void; complete: () => void }) {
  const step = sunsetSteps[state.step];
  if (!state.open) return <aside className="guide-card guide-invitation" aria-label="创作邀请"><p className="eyebrow">A SUNSET TO KEEP</p><div className="sunset-mark" aria-hidden="true">☼</div><h2>记住一场<br/>旅行的日落。</h2><p>从一片暖色天空开始，<br/>把水面的光留在画里。</p><button className="guide-primary" onClick={start}>{state.theme ? '继续旅行日落引导' : '画一幅旅行日落'}</button><p className="guide-footnote">也可以直接自由绘画。<br/>提示随时可关闭，画面由你决定。</p></aside>;
  const next = () => state.step < sunsetSteps.length - 1 ? change({ ...state, step: state.step + 1 }) : complete();
  return <aside className="guide-card" aria-label="旅行日落引导"><div className="guide-top"><p className="eyebrow">YOUR TRAVEL SUNSET</p><button onClick={() => change({ ...state, open: false })} aria-label="关闭引导">×</button></div><h2>一场日落，四次停留。</h2><ol className="guide-steps">{sunsetSteps.map((s, i) => <li key={s.title}><button aria-current={i === state.step ? 'step' : undefined} onClick={() => change({ ...state, step: i })}><span>0{i + 1}</span>{s.title}</button></li>)}</ol><div className="guide-detail"><h3>{step.title}</h3><p className="guide-area">{step.area}</p><p>{step.hint}</p><div className="guide-recipe"><i style={{ background: step.brush.color }}/><span>{step.colorName} · {step.brush.size} px · {Math.round(step.brush.load! * 100)}%</span></div><button className="guide-secondary" onClick={() => recommend(step.brush)}>采用本步建议</button><p className="guide-footnote">只调整画笔，不自动落笔。<br/>你仍可随时改变颜色与参数。</p></div><label className="guide-toggle"><input type="checkbox" checked={state.overlay} onChange={e => change({ ...state, overlay: e.target.checked })}/>显示辅助轮廓</label><div className="guide-navigation"><button disabled={!state.step} onClick={() => change({ ...state, step: state.step - 1 })}>返回上步</button><button onClick={next}>跳过本步</button></div><button className="guide-primary" onClick={next}>{state.step === 3 ? '完成引导' : '继续下一步'}</button></aside>;
}

// An SVG sibling of the renderer canvases; it never reads or writes paint arrays.
export function GuideOverlay({ step }: { step: number }) {
  return <svg className="guide-overlay" data-testid="guide-overlay" viewBox="0 0 1024 1024" aria-hidden="true"><g fill="none" stroke="#695e47" strokeOpacity=".55" strokeWidth="2" strokeDasharray="10 10"><path d="M50 520H974"/>{step === 0 && <><path d="M90 140H930M90 350H930"/><circle cx="560" cy="415" r="45"/></>}{step === 1 && <path d="M50 525 205 460 325 495 415 410 570 510 740 450 974 525"/>}{step === 2 && <path d="M80 620H940M80 780H940M80 920H940"/>}{step === 3 && <path d="m540 570-100 360m140-360 100 360M510 610h100m-130 110h160m-190 110h220"/>}</g><text x="55" y="505" fill="#695e47" opacity=".6" fontSize="17">辅助轮廓 · 不会导出</text></svg>;
}
